package com.tradeshift.exercise.nodeapi.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Node implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "parent_id", nullable = true)
    private Node parent;

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "root_id", nullable = true)
    private Node root;

    private int height;

    /**
     * Default constructor.
     */
    public Node() {
    }

    /**
     * Constructor with all attributes but the id, which is auto-generated by the persistence layer.
     * @param parent
     * @param root
     * @param height
     */
    public Node(Node parent, Node root, int height) {
        this.parent = parent;
        this.root = root;
        this.height = height;
    }

    // getters and setters //

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Node getParent() {
        return parent;
    }

    public void setParent(Node parent) {
        this.parent = parent;
    }

    public Node getRoot() {
        return root;
    }

    public void setRoot(Node root) {
        this.root = root;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    @Override
    public String toString() {
        return "Node{" +
                "id=" + id +
                ", parent=" + parent +
                ", root=" + root +
                ", height=" + height +
                '}';
    }
}